/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as PickRouteImport } from './routes/pick'
import { Route as PayRouteImport } from './routes/pay'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as Gw2RouteImport } from './routes/gw2'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminPanelRouteImport } from './routes/admin.panel'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicCronCheckRemindersRouteImport } from './routes/api/public/cron/check-reminders'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PickRoute = PickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const Gw2Route = Gw2RouteImport.update({
  id: '/gw2',
  path: '/gw2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/panel',
  path: '/admin/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCheckRemindersRoute =
  ApiPublicCronCheckRemindersRouteImport.update({
    id: '/api/public/cron/check-reminders',
    path: '/api/public/cron/check-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gw2': typeof Gw2Route
  '/how-it-works': typeof HowItWorksRoute
  '/pay': typeof PayRoute
  '/pick': typeof PickRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/panel': typeof AdminPanelRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/check-reminders': typeof ApiPublicCronCheckRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gw2': typeof Gw2Route
  '/how-it-works': typeof HowItWorksRoute
  '/pay': typeof PayRoute
  '/pick': typeof PickRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/panel': typeof AdminPanelRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin': typeof AdminIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/check-reminders': typeof ApiPublicCronCheckRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/gw2': typeof Gw2Route
  '/how-it-works': typeof HowItWorksRoute
  '/pay': typeof PayRoute
  '/pick': typeof PickRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/panel': typeof AdminPanelRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/check-reminders': typeof ApiPublicCronCheckRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gw2'
    | '/how-it-works'
    | '/pay'
    | '/pick'
    | '/unsubscribe'
    | '/welcome'
    | '/dashboard'
    | '/admin/panel'
    | '/email/unsubscribe'
    | '/admin/'
    | '/lovable/email/suppression'
    | '/api/public/cron/check-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gw2'
    | '/how-it-works'
    | '/pay'
    | '/pick'
    | '/unsubscribe'
    | '/welcome'
    | '/dashboard'
    | '/admin/panel'
    | '/email/unsubscribe'
    | '/admin'
    | '/lovable/email/suppression'
    | '/api/public/cron/check-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/gw2'
    | '/how-it-works'
    | '/pay'
    | '/pick'
    | '/unsubscribe'
    | '/welcome'
    | '/_authenticated/dashboard'
    | '/admin/panel'
    | '/email/unsubscribe'
    | '/admin/'
    | '/lovable/email/suppression'
    | '/api/public/cron/check-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  Gw2Route: typeof Gw2Route
  HowItWorksRoute: typeof HowItWorksRoute
  PayRoute: typeof PayRoute
  PickRoute: typeof PickRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminPanelRoute: typeof AdminPanelRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronCheckRemindersRoute: typeof ApiPublicCronCheckRemindersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick': {
      id: '/pick'
      path: '/pick'
      fullPath: '/pick'
      preLoaderRoute: typeof PickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gw2': {
      id: '/gw2'
      path: '/gw2'
      fullPath: '/gw2'
      preLoaderRoute: typeof Gw2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/panel': {
      id: '/admin/panel'
      path: '/admin/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-reminders': {
      id: '/api/public/cron/check-reminders'
      path: '/api/public/cron/check-reminders'
      fullPath: '/api/public/cron/check-reminders'
      preLoaderRoute: typeof ApiPublicCronCheckRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  Gw2Route: Gw2Route,
  HowItWorksRoute: HowItWorksRoute,
  PayRoute: PayRoute,
  PickRoute: PickRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WelcomeRoute: WelcomeRoute,
  AdminPanelRoute: AdminPanelRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AdminIndexRoute: AdminIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronCheckRemindersRoute: ApiPublicCronCheckRemindersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
