/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PickRouteImport } from './routes/pick'
import { Route as PayRouteImport } from './routes/pay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LastManStandingRouteImport } from './routes/last-man-standing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DetailsAddRouteImport } from './routes/details-add'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug.index'
import { Route as StripeReturnRouteImport } from './routes/stripe.return'
import { Route as OneshotclubMasterRouteImport } from './routes/oneshotclub.Master'
import { Route as LastManStandingThanksRouteImport } from './routes/last-man-standing.thanks'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DevLoginRouteImport } from './routes/dev.login'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as AdminPanelRouteImport } from './routes/admin.panel'
import { Route as AdminNextGameweekPreviewRouteImport } from './routes/admin.next-gameweek-preview'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as TenantSlugSelectionsTrackerRouteImport } from './routes/$tenantSlug.selections-tracker'
import { Route as TenantSlugAdminRouteImport } from './routes/$tenantSlug.admin'
import { Route as OneshotclubMasterIndexRouteImport } from './routes/oneshotclub.Master.index'
import { Route as TenantSlugCompSlugIndexRouteImport } from './routes/$tenantSlug.$compSlug.index'
import { Route as StripeConnectReturnRouteImport } from './routes/stripe.connect.return'
import { Route as StripeConnectRefreshRouteImport } from './routes/stripe.connect.refresh'
import { Route as OneshotclubMasterAdminRouteImport } from './routes/oneshotclub.Master.admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedPlatformAdminRouteImport } from './routes/_authenticated/platform.admin'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTenantAssetsSplatRouteImport } from './routes/api/public/tenant-assets/$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronSyncFplResultsRouteImport } from './routes/api/public/cron/sync-fpl-results'
import { Route as ApiPublicCronCheckRemindersRouteImport } from './routes/api/public/cron/check-reminders'
import { Route as AuthenticatedDashboardCompetitionsNewRouteImport } from './routes/_authenticated/dashboard.competitions.new'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PickRoute = PickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LastManStandingRoute = LastManStandingRouteImport.update({
  id: '/last-man-standing',
  path: '/last-man-standing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsAddRoute = DetailsAddRouteImport.update({
  id: '/details-add',
  path: '/details-add',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/$tenantSlug/',
  path: '/$tenantSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeReturnRoute = StripeReturnRouteImport.update({
  id: '/stripe/return',
  path: '/stripe/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OneshotclubMasterRoute = OneshotclubMasterRouteImport.update({
  id: '/oneshotclub/Master',
  path: '/oneshotclub/Master',
  getParentRoute: () => rootRouteImport,
} as any)
const LastManStandingThanksRoute = LastManStandingThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => LastManStandingRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev/login',
  path: '/dev/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/panel',
  path: '/admin/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNextGameweekPreviewRoute =
  AdminNextGameweekPreviewRouteImport.update({
    id: '/admin/next-gameweek-preview',
    path: '/admin/next-gameweek-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TenantSlugSelectionsTrackerRoute =
  TenantSlugSelectionsTrackerRouteImport.update({
    id: '/$tenantSlug/selections-tracker',
    path: '/$tenantSlug/selections-tracker',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantSlugAdminRoute = TenantSlugAdminRouteImport.update({
  id: '/$tenantSlug/admin',
  path: '/$tenantSlug/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OneshotclubMasterIndexRoute = OneshotclubMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OneshotclubMasterRoute,
} as any)
const TenantSlugCompSlugIndexRoute = TenantSlugCompSlugIndexRouteImport.update({
  id: '/$tenantSlug/$compSlug/',
  path: '/$tenantSlug/$compSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeConnectReturnRoute = StripeConnectReturnRouteImport.update({
  id: '/stripe/connect/return',
  path: '/stripe/connect/return',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeConnectRefreshRoute = StripeConnectRefreshRouteImport.update({
  id: '/stripe/connect/refresh',
  path: '/stripe/connect/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const OneshotclubMasterAdminRoute = OneshotclubMasterAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OneshotclubMasterRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformAdminRoute =
  AuthenticatedPlatformAdminRouteImport.update({
    id: '/platform/admin',
    path: '/platform/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTenantAssetsSplatRoute =
  ApiPublicTenantAssetsSplatRouteImport.update({
    id: '/api/public/tenant-assets/$',
    path: '/api/public/tenant-assets/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncFplResultsRoute =
  ApiPublicCronSyncFplResultsRouteImport.update({
    id: '/api/public/cron/sync-fpl-results',
    path: '/api/public/cron/sync-fpl-results',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCheckRemindersRoute =
  ApiPublicCronCheckRemindersRouteImport.update({
    id: '/api/public/cron/check-reminders',
    path: '/api/public/cron/check-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardCompetitionsNewRoute =
  AuthenticatedDashboardCompetitionsNewRouteImport.update({
    id: '/competitions/new',
    path: '/competitions/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/details': typeof DetailsRoute
  '/details-add': typeof DetailsAddRoute
  '/how-it-works': typeof HowItWorksRoute
  '/last-man-standing': typeof LastManStandingRouteWithChildren
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/pick': typeof PickRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/$tenantSlug/admin': typeof TenantSlugAdminRoute
  '/$tenantSlug/selections-tracker': typeof TenantSlugSelectionsTrackerRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/next-gameweek-preview': typeof AdminNextGameweekPreviewRoute
  '/admin/panel': typeof AdminPanelRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/dev/login': typeof DevLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/last-man-standing/thanks': typeof LastManStandingThanksRoute
  '/oneshotclub/Master': typeof OneshotclubMasterRouteWithChildren
  '/stripe/return': typeof StripeReturnRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/platform/admin': typeof AuthenticatedPlatformAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/oneshotclub/Master/admin': typeof OneshotclubMasterAdminRoute
  '/stripe/connect/refresh': typeof StripeConnectRefreshRoute
  '/stripe/connect/return': typeof StripeConnectReturnRoute
  '/$tenantSlug/$compSlug/': typeof TenantSlugCompSlugIndexRoute
  '/oneshotclub/Master/': typeof OneshotclubMasterIndexRoute
  '/dashboard/competitions/new': typeof AuthenticatedDashboardCompetitionsNewRoute
  '/api/public/cron/check-reminders': typeof ApiPublicCronCheckRemindersRoute
  '/api/public/cron/sync-fpl-results': typeof ApiPublicCronSyncFplResultsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tenant-assets/$': typeof ApiPublicTenantAssetsSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/details': typeof DetailsRoute
  '/details-add': typeof DetailsAddRoute
  '/how-it-works': typeof HowItWorksRoute
  '/last-man-standing': typeof LastManStandingRouteWithChildren
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/pick': typeof PickRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/$tenantSlug/admin': typeof TenantSlugAdminRoute
  '/$tenantSlug/selections-tracker': typeof TenantSlugSelectionsTrackerRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/next-gameweek-preview': typeof AdminNextGameweekPreviewRoute
  '/admin/panel': typeof AdminPanelRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/dev/login': typeof DevLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/last-man-standing/thanks': typeof LastManStandingThanksRoute
  '/stripe/return': typeof StripeReturnRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/platform/admin': typeof AuthenticatedPlatformAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/oneshotclub/Master/admin': typeof OneshotclubMasterAdminRoute
  '/stripe/connect/refresh': typeof StripeConnectRefreshRoute
  '/stripe/connect/return': typeof StripeConnectReturnRoute
  '/$tenantSlug/$compSlug': typeof TenantSlugCompSlugIndexRoute
  '/oneshotclub/Master': typeof OneshotclubMasterIndexRoute
  '/dashboard/competitions/new': typeof AuthenticatedDashboardCompetitionsNewRoute
  '/api/public/cron/check-reminders': typeof ApiPublicCronCheckRemindersRoute
  '/api/public/cron/sync-fpl-results': typeof ApiPublicCronSyncFplResultsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tenant-assets/$': typeof ApiPublicTenantAssetsSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/details': typeof DetailsRoute
  '/details-add': typeof DetailsAddRoute
  '/how-it-works': typeof HowItWorksRoute
  '/last-man-standing': typeof LastManStandingRouteWithChildren
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/pick': typeof PickRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/$tenantSlug/admin': typeof TenantSlugAdminRoute
  '/$tenantSlug/selections-tracker': typeof TenantSlugSelectionsTrackerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/next-gameweek-preview': typeof AdminNextGameweekPreviewRoute
  '/admin/panel': typeof AdminPanelRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/dev/login': typeof DevLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/last-man-standing/thanks': typeof LastManStandingThanksRoute
  '/oneshotclub/Master': typeof OneshotclubMasterRouteWithChildren
  '/stripe/return': typeof StripeReturnRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/_authenticated/platform/admin': typeof AuthenticatedPlatformAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/oneshotclub/Master/admin': typeof OneshotclubMasterAdminRoute
  '/stripe/connect/refresh': typeof StripeConnectRefreshRoute
  '/stripe/connect/return': typeof StripeConnectReturnRoute
  '/$tenantSlug/$compSlug/': typeof TenantSlugCompSlugIndexRoute
  '/oneshotclub/Master/': typeof OneshotclubMasterIndexRoute
  '/_authenticated/dashboard/competitions/new': typeof AuthenticatedDashboardCompetitionsNewRoute
  '/api/public/cron/check-reminders': typeof ApiPublicCronCheckRemindersRoute
  '/api/public/cron/sync-fpl-results': typeof ApiPublicCronSyncFplResultsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tenant-assets/$': typeof ApiPublicTenantAssetsSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/details'
    | '/details-add'
    | '/how-it-works'
    | '/last-man-standing'
    | '/login'
    | '/pay'
    | '/pick'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/welcome'
    | '/$tenantSlug/admin'
    | '/$tenantSlug/selections-tracker'
    | '/dashboard'
    | '/onboarding'
    | '/admin/next-gameweek-preview'
    | '/admin/panel'
    | '/case-studies/$slug'
    | '/dev/login'
    | '/email/unsubscribe'
    | '/last-man-standing/thanks'
    | '/oneshotclub/Master'
    | '/stripe/return'
    | '/$tenantSlug/'
    | '/case-studies/'
    | '/platform/admin'
    | '/lovable/email/suppression'
    | '/oneshotclub/Master/admin'
    | '/stripe/connect/refresh'
    | '/stripe/connect/return'
    | '/$tenantSlug/$compSlug/'
    | '/oneshotclub/Master/'
    | '/dashboard/competitions/new'
    | '/api/public/cron/check-reminders'
    | '/api/public/cron/sync-fpl-results'
    | '/api/public/payments/webhook'
    | '/api/public/tenant-assets/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/details'
    | '/details-add'
    | '/how-it-works'
    | '/last-man-standing'
    | '/login'
    | '/pay'
    | '/pick'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/welcome'
    | '/$tenantSlug/admin'
    | '/$tenantSlug/selections-tracker'
    | '/dashboard'
    | '/onboarding'
    | '/admin/next-gameweek-preview'
    | '/admin/panel'
    | '/case-studies/$slug'
    | '/dev/login'
    | '/email/unsubscribe'
    | '/last-man-standing/thanks'
    | '/stripe/return'
    | '/$tenantSlug'
    | '/case-studies'
    | '/platform/admin'
    | '/lovable/email/suppression'
    | '/oneshotclub/Master/admin'
    | '/stripe/connect/refresh'
    | '/stripe/connect/return'
    | '/$tenantSlug/$compSlug'
    | '/oneshotclub/Master'
    | '/dashboard/competitions/new'
    | '/api/public/cron/check-reminders'
    | '/api/public/cron/sync-fpl-results'
    | '/api/public/payments/webhook'
    | '/api/public/tenant-assets/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/details'
    | '/details-add'
    | '/how-it-works'
    | '/last-man-standing'
    | '/login'
    | '/pay'
    | '/pick'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/welcome'
    | '/$tenantSlug/admin'
    | '/$tenantSlug/selections-tracker'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/admin/next-gameweek-preview'
    | '/admin/panel'
    | '/case-studies/$slug'
    | '/dev/login'
    | '/email/unsubscribe'
    | '/last-man-standing/thanks'
    | '/oneshotclub/Master'
    | '/stripe/return'
    | '/$tenantSlug/'
    | '/case-studies/'
    | '/_authenticated/platform/admin'
    | '/lovable/email/suppression'
    | '/oneshotclub/Master/admin'
    | '/stripe/connect/refresh'
    | '/stripe/connect/return'
    | '/$tenantSlug/$compSlug/'
    | '/oneshotclub/Master/'
    | '/_authenticated/dashboard/competitions/new'
    | '/api/public/cron/check-reminders'
    | '/api/public/cron/sync-fpl-results'
    | '/api/public/payments/webhook'
    | '/api/public/tenant-assets/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DetailsRoute: typeof DetailsRoute
  DetailsAddRoute: typeof DetailsAddRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LastManStandingRoute: typeof LastManStandingRouteWithChildren
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRoute
  PickRoute: typeof PickRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WelcomeRoute: typeof WelcomeRoute
  TenantSlugAdminRoute: typeof TenantSlugAdminRoute
  TenantSlugSelectionsTrackerRoute: typeof TenantSlugSelectionsTrackerRoute
  AdminNextGameweekPreviewRoute: typeof AdminNextGameweekPreviewRoute
  AdminPanelRoute: typeof AdminPanelRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  DevLoginRoute: typeof DevLoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  OneshotclubMasterRoute: typeof OneshotclubMasterRouteWithChildren
  StripeReturnRoute: typeof StripeReturnRoute
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  StripeConnectRefreshRoute: typeof StripeConnectRefreshRoute
  StripeConnectReturnRoute: typeof StripeConnectReturnRoute
  TenantSlugCompSlugIndexRoute: typeof TenantSlugCompSlugIndexRoute
  ApiPublicCronCheckRemindersRoute: typeof ApiPublicCronCheckRemindersRoute
  ApiPublicCronSyncFplResultsRoute: typeof ApiPublicCronSyncFplResultsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTenantAssetsSplatRoute: typeof ApiPublicTenantAssetsSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick': {
      id: '/pick'
      path: '/pick'
      fullPath: '/pick'
      preLoaderRoute: typeof PickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-man-standing': {
      id: '/last-man-standing'
      path: '/last-man-standing'
      fullPath: '/last-man-standing'
      preLoaderRoute: typeof LastManStandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details-add': {
      id: '/details-add'
      path: '/details-add'
      fullPath: '/details-add'
      preLoaderRoute: typeof DetailsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe/return': {
      id: '/stripe/return'
      path: '/stripe/return'
      fullPath: '/stripe/return'
      preLoaderRoute: typeof StripeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneshotclub/Master': {
      id: '/oneshotclub/Master'
      path: '/oneshotclub/Master'
      fullPath: '/oneshotclub/Master'
      preLoaderRoute: typeof OneshotclubMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-man-standing/thanks': {
      id: '/last-man-standing/thanks'
      path: '/thanks'
      fullPath: '/last-man-standing/thanks'
      preLoaderRoute: typeof LastManStandingThanksRouteImport
      parentRoute: typeof LastManStandingRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/login': {
      id: '/dev/login'
      path: '/dev/login'
      fullPath: '/dev/login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/panel': {
      id: '/admin/panel'
      path: '/admin/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/next-gameweek-preview': {
      id: '/admin/next-gameweek-preview'
      path: '/admin/next-gameweek-preview'
      fullPath: '/admin/next-gameweek-preview'
      preLoaderRoute: typeof AdminNextGameweekPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$tenantSlug/selections-tracker': {
      id: '/$tenantSlug/selections-tracker'
      path: '/$tenantSlug/selections-tracker'
      fullPath: '/$tenantSlug/selections-tracker'
      preLoaderRoute: typeof TenantSlugSelectionsTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/admin': {
      id: '/$tenantSlug/admin'
      path: '/$tenantSlug/admin'
      fullPath: '/$tenantSlug/admin'
      preLoaderRoute: typeof TenantSlugAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneshotclub/Master/': {
      id: '/oneshotclub/Master/'
      path: '/'
      fullPath: '/oneshotclub/Master/'
      preLoaderRoute: typeof OneshotclubMasterIndexRouteImport
      parentRoute: typeof OneshotclubMasterRoute
    }
    '/$tenantSlug/$compSlug/': {
      id: '/$tenantSlug/$compSlug/'
      path: '/$tenantSlug/$compSlug'
      fullPath: '/$tenantSlug/$compSlug/'
      preLoaderRoute: typeof TenantSlugCompSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe/connect/return': {
      id: '/stripe/connect/return'
      path: '/stripe/connect/return'
      fullPath: '/stripe/connect/return'
      preLoaderRoute: typeof StripeConnectReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe/connect/refresh': {
      id: '/stripe/connect/refresh'
      path: '/stripe/connect/refresh'
      fullPath: '/stripe/connect/refresh'
      preLoaderRoute: typeof StripeConnectRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneshotclub/Master/admin': {
      id: '/oneshotclub/Master/admin'
      path: '/admin'
      fullPath: '/oneshotclub/Master/admin'
      preLoaderRoute: typeof OneshotclubMasterAdminRouteImport
      parentRoute: typeof OneshotclubMasterRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/admin': {
      id: '/_authenticated/platform/admin'
      path: '/platform/admin'
      fullPath: '/platform/admin'
      preLoaderRoute: typeof AuthenticatedPlatformAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tenant-assets/$': {
      id: '/api/public/tenant-assets/$'
      path: '/api/public/tenant-assets/$'
      fullPath: '/api/public/tenant-assets/$'
      preLoaderRoute: typeof ApiPublicTenantAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-fpl-results': {
      id: '/api/public/cron/sync-fpl-results'
      path: '/api/public/cron/sync-fpl-results'
      fullPath: '/api/public/cron/sync-fpl-results'
      preLoaderRoute: typeof ApiPublicCronSyncFplResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-reminders': {
      id: '/api/public/cron/check-reminders'
      path: '/api/public/cron/check-reminders'
      fullPath: '/api/public/cron/check-reminders'
      preLoaderRoute: typeof ApiPublicCronCheckRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/competitions/new': {
      id: '/_authenticated/dashboard/competitions/new'
      path: '/competitions/new'
      fullPath: '/dashboard/competitions/new'
      preLoaderRoute: typeof AuthenticatedDashboardCompetitionsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCompetitionsNewRoute: typeof AuthenticatedDashboardCompetitionsNewRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCompetitionsNewRoute:
      AuthenticatedDashboardCompetitionsNewRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlatformAdminRoute: typeof AuthenticatedPlatformAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlatformAdminRoute: AuthenticatedPlatformAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LastManStandingRouteChildren {
  LastManStandingThanksRoute: typeof LastManStandingThanksRoute
}

const LastManStandingRouteChildren: LastManStandingRouteChildren = {
  LastManStandingThanksRoute: LastManStandingThanksRoute,
}

const LastManStandingRouteWithChildren = LastManStandingRoute._addFileChildren(
  LastManStandingRouteChildren,
)

interface OneshotclubMasterRouteChildren {
  OneshotclubMasterAdminRoute: typeof OneshotclubMasterAdminRoute
  OneshotclubMasterIndexRoute: typeof OneshotclubMasterIndexRoute
}

const OneshotclubMasterRouteChildren: OneshotclubMasterRouteChildren = {
  OneshotclubMasterAdminRoute: OneshotclubMasterAdminRoute,
  OneshotclubMasterIndexRoute: OneshotclubMasterIndexRoute,
}

const OneshotclubMasterRouteWithChildren =
  OneshotclubMasterRoute._addFileChildren(OneshotclubMasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DetailsRoute: DetailsRoute,
  DetailsAddRoute: DetailsAddRoute,
  HowItWorksRoute: HowItWorksRoute,
  LastManStandingRoute: LastManStandingRouteWithChildren,
  LoginRoute: LoginRoute,
  PayRoute: PayRoute,
  PickRoute: PickRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WelcomeRoute: WelcomeRoute,
  TenantSlugAdminRoute: TenantSlugAdminRoute,
  TenantSlugSelectionsTrackerRoute: TenantSlugSelectionsTrackerRoute,
  AdminNextGameweekPreviewRoute: AdminNextGameweekPreviewRoute,
  AdminPanelRoute: AdminPanelRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  DevLoginRoute: DevLoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  OneshotclubMasterRoute: OneshotclubMasterRouteWithChildren,
  StripeReturnRoute: StripeReturnRoute,
  TenantSlugIndexRoute: TenantSlugIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  StripeConnectRefreshRoute: StripeConnectRefreshRoute,
  StripeConnectReturnRoute: StripeConnectReturnRoute,
  TenantSlugCompSlugIndexRoute: TenantSlugCompSlugIndexRoute,
  ApiPublicCronCheckRemindersRoute: ApiPublicCronCheckRemindersRoute,
  ApiPublicCronSyncFplResultsRoute: ApiPublicCronSyncFplResultsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTenantAssetsSplatRoute: ApiPublicTenantAssetsSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
